### ISSUE TITLE
Adicionar página sobre Código de Conduta

### ISSUE THREAD

**Issue by julianyraiol** [pythonbrasil/pybr2022-site#22]
O texto da página deve ser de acordo com o que está descrito nesse [documento](https://docs.google.com/document/d/1dM-FmvkIJwCF5nJF0wBmsKsZ9tlNbNyCQw06bCldHU4/edit)

Layout definido: https://www.figma.com/file/mNxbwSMw0ugpJhetfYCi3M/Phyton-Brasil-2022?node-id=3%3A77

**Comment by alynnefs** [comment]
podem me colocar nesse (vou pegando mais na medida que conseguir entregar)

**Comment by julianyraiol** [comment]
oi @alynnefs a gente conseguiu adicionar, está aqui nessa branch

https://github.com/pythonbrasil/pybr2022-site/tree/develop

**Comment by julianyraiol** [comment]
a gente tem uma página parecida com essa aqui na issue https://github.com/pythonbrasil/pybr2022-site/issues/21
