### ISSUE TITLE
Ajustes v0

### ISSUE THREAD

**Issue by rougeth** [pythonbrasil/pybr2022-site#24]
- [x] Tá sem a logo do site lá em cima, seria legal colocar
- [x] A linha que divide a logo e o texto tá muito pequena e fina
- [x] O texto debaixo do título e o texto das redes sociais está muito pequeno, tive dificuldade de ler
- [x] E a logo do python e das redes sociais tá em baixa qualidade, é possível mudar pra svg?

**Comment by julianyraiol** [comment]
Problemas de responsividade

![photo5073651730578778765](https://user-images.githubusercontent.com/9119004/161870236-be9d4817-6151-4a1a-8381-92647eb85c3a.jpg)

**Comment by julianyraiol** [comment]
No chrome a fonte muda 

![image](https://user-images.githubusercontent.com/9119004/161870518-584ec6ae-9756-4c63-90b6-28c440ebb556.png)

**Comment by alencarftc** [comment]
Abri um [pull request](https://github.com/pythonbrasil/pybr2022-site/pull/26) que realiza as devidas correções.
