### ISSUE TITLE
Adicionar modo responsivo na versão 1

### ISSUE THREAD

**Issue by julianyraiol** [pythonbrasil/pybr2022-site#30]
branch da versão 1: https://github.com/pythonbrasil/pybr2022-site/tree/v1-gatsby
mobile: https://www.figma.com/file/mNxbwSMw0ugpJhetfYCi3M/Phyton-Brasil-2022?node-id=6%3A6

**Comment by julianyraiol** [comment]
Seções que ainda precisam de ajustes
- Header
- FAQ

![image](https://user-images.githubusercontent.com/9119004/170150293-87ac0102-457e-4753-a5d8-eee99ae8d463.png)

**Comment by alencarftc** [comment]
#69

**Comment by alencarftc** [comment]
#69
