### ISSUE TITLE
Arrumar link do plano de patrocínio

### ISSUE THREAD

**Issue by rougeth** [pythonbrasil/pybr2022-site#65]
Link anterior:
https://2022.pythonbrasil.org.br/assets/patrocinio_python_brasil.pdf

Link no Gatsby:
https://2022.pythonbrasil.org.br/static/patrocinio_python_brasil_ptbr-6ed512a41579cfea596d03d6453816dd.pdf

**Comment by alynnefs** [comment]
ainda precisa mudar esse link?

**Comment by rougeth** [comment]
Acho que não fez diferença até agora, podemos fechar.
